Update documentation on logout
bcc-code/bcc-code.github.io pull request #51
Opened 2022-12-08 11:55 UTC by JakubC-projects

Updates the documentation regarding the Single Log Out, explaining how the implement the backchannel logout (which is our current stratagegy for SLO)

2022-12-08 15:34 UTC, rvanoord requested changes

2022-12-08 15:34 UTC, rvanoord commented on _docs/signon/openid-connect.md
> +**WordPress applications that have the ``BCC Signon`` plugin installed should not follow this tutorial (single logout
"BCC Login" is the name of the new plugin (you could add a link to the releases page on github --bcc-wp repo)

2022-12-08 15:34 UTC, rvanoord commented on _docs/signon/openid-connect.md
> +# Single logout
Could also mention that the logout url needs to be registered centrally (in auth0).. ie. need to send it to it@bcc.no.

In addition, you could link to the oidc signout specification and/or the documentation from auth0

2022-12-09 07:41 UTC, JakubC-projects commented on _docs/signon/openid-connect.md
> +# Single logout
It is described in the Backchannel logout explanation part https://github.com/bcc-code/bcc-code.github.io/pull/51/files#diff-2882e0a12b5e36041f56bf7d45f56a55acf247f8f6a912532d45432a8d26cab3R381

2022-12-09 07:44 UTC, JakubC-projects commented on _docs/signon/openid-connect.md
> +# Single logout
I don't think auth0 provides a documentation as it's a beta feature, but I included an architecture diagram and now added a link to the oidc documentation

2022-12-09 07:45 UTC, JakubC-projects commented on _docs/signon/openid-connect.md
> +**WordPress applications that have the ``BCC Signon`` plugin installed should not follow this tutorial (single logout
added

2022-12-09 07:52 UTC, rvanoord approved these changes

2022-12-09 07:52 UTC, merged