Technology Radar
bcc-code/bcc-code.github.io pull request #66
Opened 2023-02-12 13:20 UTC by jacobe

Added a description for the technology radar.
Please add your comments and/or suggestions.
If you want to add more technologies later you can just make new PRs.

PS. I made this into a PR to spawn a discussion in the community.

2023-02-13 08:51 UTC, kkuepper approved these changes

2023-02-13 08:55 UTC, kkuepper commented
Flutter should be added (trial or adopt)

2023-02-13 09:14 UTC, kkuepper commented
@rvanoord Is Google Analytics a hold? And what should we use instead?

2023-02-13 09:27 UTC, KillerX commented
Agree with @kkuepper on Flutter, Xamarin (Xamarin support will end on May 1, 2024 for all Xamarin SDKs), and MAUI as the replacement for Xamarin.

Ref GA: There are several countries that have found GA to be in breach of privacy laws, but it is also worth nothing that the "new" version called "Google Analytics 4" is supposedly a separate product that does not suffer from the same issues, but that has not been confirmed from a legal/court standpoint to my knowledge.

https://www.gpdp.it/web/guest/home/docweb/-/docweb-display/docweb/9782874#english
https://www.euractiv.com/section/data-protection/news/france-joins-austria-says-google-analytics-data-not-protected-in-us/
https://noyb.eu/en/austrian-dsb-eu-us-data-transfers-google-analytics-illegal

2023-02-13 09:42 UTC, KillerX approved these changes

2023-02-13 11:55 UTC, akselkvitberg commented
Regarding Google Analytics and use in Norway: https://www.datatilsynet.no/aktuelt/aktuelle-nyheter-2022/google-analytics-kan-vare-ulovlig/

We use https://matomo.org/ at work.

2023-02-13 14:45 UTC, kkuepper commented on .vuepress/components/tech-radar.js
> +        name: 'Xamarin',
Maybe it's better to call it ".NET for iOS and Android" instead of Xamarin, since the brand name Xamarin is dead. But the underlying technology to run .NET on iOS and Android will continue to live in .NET 7 and forward.
Nevertheless, I think it should be "hold" since MAUI or Flutter are better for new projects.

2023-02-13 15:21 UTC, kkuepper requested changes
rename Xamarin

2023-02-13 16:41 UTC, jacobe commented on .vuepress/components/tech-radar.js
> +        name: 'Xamarin',
Done

2023-02-13 17:57 UTC, kkuepper approved these changes

2023-02-13 19:40 UTC, Ghostbird commented
> rename Xamarin

I wouldn't do that in this way. Xamarin is deprecated, MAUI is its not-exactly-drop-in replacement. That both use the .NET for iOS / Android technology under the hood is knowledge only those who have worked with Xamarin and MAUI in more depth will know. A developer will generally be presented with a choice that involves Xamarin or MAUI. Then the tech radar can help drive the choice.

We might note these kind of things in a more detailed part on technologies we use, but I'd recommend against using it on the radar..

2023-02-13 20:10 UTC, Ghostbird commented
> Flutter should be added (trial or adopt). Xamarin is probably hold. .NET MAUI (Multi-plattform App UI) might be interesting in the future. Does that make it assess?

I'd put MAUI in the assess category most definitely. We know it exists. We have developers that can use it (such as I), but we haven't used it for BCC IT yet, and the main question is whether there will be a situation where it's the right choice for a BCC IT project.

- It's definitely known and therefore should be on the radar
- It's definitely not in the Hold or Adopt categories
- We don't use it yet, so it's not Trial either.
- By elimination it must be Assess, and that conclusion makes sense to me.

2023-02-14 07:59 UTC, jacobe commented on .vuepress/components/tech-radar.js
> +        category: 'tools',
Typescript should be under "languages"

2023-02-14 07:59 UTC, jacobe commented on .vuepress/components/tech-radar.js
> +        category: 'databases',
Do we need the new category? Could perhaps just put it under "tools"

2023-02-14 08:52 UTC, kkuepper commented on .vuepress/components/tech-radar.js
> +        category: 'databases',
We have MSSQL, RavenDB, ArangoDB, Firebase in active use.
CosmosDB, MongoDB are used widely in the industry.

2023-02-14 08:59 UTC, kkuepper commented
> > rename Xamarin
> 
> I wouldn't do that in this way. Xamarin is deprecated, MAUI is its not-exactly-drop-in replacement. That both use the .NET for iOS / Android technology under the hood is knowledge only those who have worked with Xamarin and MAUI in more depth will know. A developer will generally be presented with a choice that involves Xamarin or MAUI. Then the tech radar can help drive the choice.
> 
> We might note these kind of things in a more detailed part on technologies we use, but I'd recommend against using it on the radar..

My thinking was that, if we call it Xamarin and someone googles Xamarin they might get the impression that we need to start rewriting the BMM app ASAP, since the support expires by the time a new app can be written. But that's not true since .NET for iOS and Android will be supported for a long time.
But that kind of nuance doesn't necessarily belong on the Tech Radar. I think the current solution '.NET for iOS and Android (Xamarin)' is precise and understandable.

2023-02-14 10:57 UTC, rvanoord commented
> @rvanoord Is Google Analytics a hold? And what should we use instead?

Agree that "Google Analytics" should be "hold" due to uncertainties with GDPR

2023-02-14 11:00 UTC, rvanoord commented on .vuepress/components/tech-radar.js
> +        status: 'assess'
I would probaby put MAUI on "hold" as well. Simply because there's no need for two mobile frameworks.

2023-02-14 11:00 UTC, rvanoord commented on docs/guides/tech-radar.md
> +* **hold** - We have not had a good experience with the technology and recommend phasing it out.
not had a good experience, or the technology doesn't align with our strategy

2023-02-14 11:01 UTC, kkuepper commented on .vuepress/components/tech-radar.js
> +        status: 'assess'
If we put it on hold it sounds like we looked at it and decided against it. Then it's better to not list it at all.

2023-02-14 11:02 UTC, Ghostbird commented on docs/guides/tech-radar.md
> +* **hold** - We have not had a good experience with the technology and recommend phasing it out.
Ah, we could say that we've hereby assessed it, and put it into the _Hold_ category, because of strategic conflicts. Makes sense.

2023-02-14 15:12 UTC, u12206050 commented on .vuepress/components/tech-radar.js
> +        category: 'databases',
I agree, fill it in @kkuepper

2023-02-14 16:41 UTC, andreasgan commented on .vuepress/components/tech-radar.js
> +        status: 'adpot'
```suggestion
        status: 'adopt'
```

2023-02-14 19:45 UTC, jacobe commented on .vuepress/components/tech-radar.js
> +        status: 'assess'
Yea, agree. You shouldn't just start using things that are in "assess"

2023-02-14 19:52 UTC, jacobe commented on .vuepress/components/tech-radar.js
> +        category: 'databases',
@fredrikved any opinions here? @adelinn?

2023-02-14 19:55 UTC, jacobe commented on .vuepress/components/tech-radar.js
> +        category: 'databases',
@kkuepper let's first add only the ones that are either widely used in BCC (adopt) or are perhaps used in a smaller project or two (trial)

2023-02-15 07:56 UTC, kkuepper approved these changes

2023-02-15 08:12 UTC, jacobe commented on .vuepress/components/tech-radar.js
> +        category: 'databases',
OK. I'm merging this PR now, but feel free to add the databases later @kkuepper. I don't have enough context to add them myself.

2023-02-15 08:13 UTC, merged

2023-02-17 08:04 UTC, jacobe commented on .vuepress/components/tech-radar.js
> +        category: 'databases',
Yes, please add it @adelinn